install.packages('knitr')
install.packages('MASS')
install.packages('tidyverse')
install.packages('data.table')
install.packages('dplyr') 

install.packages('readr')
install.packages('readxl')

install.packages('ggplot2')
install.packages('lattice')
install.packages('latticeExtra')
install.packages('ggpubr') 
install.packages('gridExtra')

install.packages('caret')
install.packages('kernlab')
install.packages('mlbench')
install.packages('MLmetrics')
install.packages('mlr')

install.packages('skimr')
install.packages('Boruta') 
install.packages('DMwR')  
install.packages('purrr') 
install.packages('pROC')  
install.packages('ROCR')
install.packages('Epi')
install.packages('InformationValue')

install.packages('rjson')
install.packages('mongolite')  
install.packages('plumber')