# ----------------- Carrega Pacotes ----------------------------
suppressMessages(library(knitr))
suppressMessages(library(MASS))
suppressMessages(library(tidyverse))
suppressMessages(library(dplyr)) 
suppressMessages(library(ggplot2))
suppressMessages(library(lattice))
suppressMessages(library(latticeExtra))
suppressMessages(library(ggpubr)) 
suppressMessages(library(gridExtra))

suppressMessages(library(data.table))
suppressMessages(library(readr))
suppressMessages(library(readxl))

suppressMessages(library(skimr))
suppressMessages(library(Boruta))
suppressMessages(library(caret))
suppressMessages(library(kernlab))
suppressMessages(library(mlbench))
suppressMessages(library(MLmetrics))
suppressMessages(library(mlr))

suppressMessages(library(DMwR))  
suppressMessages(library(purrr)) 
suppressMessages(library(pROC))  
suppressMessages(library(ROCR))
suppressMessages(library(Epi))
suppressMessages(library(InformationValue))

suppressMessages(library(rjson))
suppressMessages(library(mongolite))  
suppressMessages(library(plumber))
